# Site settings
title: labs.jsdev.org
description: Website about javascript development with Angular.js, Node.js, jQuery, Mongodb, Docker, Linux and etc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://labs.jsdev.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

# analytics
google_analytics: "UA-4894954-48"
